# Generated by Django 5.1.2 on 2024-10-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="recommendation_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("taken_courses", models.JSONField()),
                ("failed_courses", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
