# Generated by Django 5.1.2 on 2024-10-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_recommendation_request_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation_request",
            name="name",
        ),
    ]
