# Generated by Django 5.1.2 on 2025-03-27 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_recommendation_request_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation_request",
            old_name="semester",
            new_name="program",
        ),
        migrations.RemoveField(
            model_name="recommendation_request",
            name="failed_courses",
        ),
    ]
