# Generated by Django 5.1.2 on 2025-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_recommendationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="similarity_score",
            field=models.FloatField(default=0.0),
        ),
    ]
