# Generated by Django 5.1.2 on 2025-05-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_recommendationlog_similarity_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="total_credits",
            field=models.IntegerField(
                default=0, help_text="The total credits of the generated schedule"
            ),
        ),
        migrations.AlterField(
            model_name="recommendationlog",
            name="similarity_score",
            field=models.FloatField(
                default=0.0, help_text="The similarityScore returned by the scheduler"
            ),
        ),
    ]
