# Generated by Django 5.1.2 on 2025-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_recommendationlog_total_credits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="average_difficulty_score",
            field=models.FloatField(
                default=0.0,
                help_text="The average per-semester difficulty score of the generated schedule",
            ),
        ),
    ]
