# Generated by Django 5.1.2 on 2025-05-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_recommendationlog_average_difficulty_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation_request",
            name="next_semester",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="next_semester",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
